name: influxdb-test # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  test-pip:
    plugin: python
    source: .
    python-packages:
      - influxdb-client
    stage:
      - lib64/*

  test-dump:
    plugin: dump 
    source: .

  core-dep:
    plugin: nil
    build-packages:
      - python3-pip
      - build-essential
    stage-packages:
      - ros-noetic-roslaunch
      - python3-rospkg

  workspace:
    plugin: catkin-tools
    source: .
    catkin-tools-packages: [catkin_simple, influxdb_test]
    after: [test-pip, core-dep]

apps:
  test-pip-comm:
    command: src/influxdb.py

  catkin-ros-run:
    command: opt/ros/noetic/bin/roslaunch influxdb_test test.launch
    plugs: [network, network-bind]
    extensions: [ros1-noetic]
